# Use official MySQL image as base
FROM mysql:8.0-debian

# Set environment variables for MySQL root password and default database
#ENV MYSQL_ROOT_PASSWORD=dsa3101
#ENV MYSQL_DATABASE=sakila

COPY my.cnf /etc/mysql/my.cnf


# Expose MySQL port
EXPOSE 3306
